// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/azar-writes-code/oolio-products-backend/pkg/server/rest/models/products"
	"github.com/jackc/pgx/v5/pgtype"
)

// Orders table for the online food ordering system
type Order struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	CouponCode  *string            `db:"coupon_code" json:"coupon_code"`
	TotalAmount pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Individual items associated with an order
type OrderItem struct {
	OrderID   pgtype.UUID `db:"order_id" json:"order_id"`
	ProductID int32       `db:"product_id" json:"product_id"`
	Quantity  int32       `db:"quantity" json:"quantity"`
}

// Products table for the online food ordering system
type Product struct {
	ID          int32              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Price       pgtype.Numeric     `db:"price" json:"price"`
	Category    []string           `db:"category" json:"category"`
	Image       products.Image     `db:"image" json:"image"`
	Stock       int32              `db:"stock" json:"stock"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
