// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateOrder = `-- name: CreateOrder :one
INSERT INTO orders (coupon_code, total_amount, status)
VALUES ($1, $2, $3)
RETURNING id, coupon_code, total_amount, status, created_at, updated_at
`

type CreateOrderParams struct {
	CouponCode  *string        `db:"coupon_code" json:"coupon_code"`
	TotalAmount pgtype.Numeric `db:"total_amount" json:"total_amount"`
	Status      string         `db:"status" json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, CreateOrder, arg.CouponCode, arg.TotalAmount, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity)
VALUES ($1, $2, $3)
`

type CreateOrderItemParams struct {
	OrderID   pgtype.UUID `db:"order_id" json:"order_id"`
	ProductID int32       `db:"product_id" json:"product_id"`
	Quantity  int32       `db:"quantity" json:"quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, CreateOrderItem, arg.OrderID, arg.ProductID, arg.Quantity)
	return err
}

const GetOrderByID = `-- name: GetOrderByID :one
SELECT id, coupon_code, total_amount, status, created_at, updated_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, GetOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CouponCode,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListOrderItems = `-- name: ListOrderItems :many
SELECT product_id, quantity FROM order_items WHERE order_id = $1
`

type ListOrderItemsRow struct {
	ProductID int32 `db:"product_id" json:"product_id"`
	Quantity  int32 `db:"quantity" json:"quantity"`
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]ListOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, ListOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsRow{}
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(&i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOrders = `-- name: ListOrders :many
SELECT id, coupon_code, total_amount, status, created_at, updated_at FROM orders
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListOrdersParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageSize   int32 `db:"page_size" json:"page_size"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, ListOrders, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CouponCode,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
