// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/azar-writes-code/oolio-products-backend/pkg/server/rest/models/products"
	"github.com/jackc/pgx/v5/pgtype"
)

const CountProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateManyProducts = `-- name: CreateManyProducts :many
INSERT INTO products (name, description, price, image, category, stock)
VALUES (
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::decimal[]),
    unnest($4::product_image[]),
    string_to_array(unnest($5::text[]), '|||'),
    unnest($6::int[])
)
RETURNING id, name, description, price, category, image, stock, created_at, updated_at
`

type CreateManyProductsParams struct {
	Names        []string         `db:"names" json:"names"`
	Descriptions []string         `db:"descriptions" json:"descriptions"`
	Prices       []pgtype.Numeric `db:"prices" json:"prices"`
	Images       []products.Image `db:"images" json:"images"`
	Categories   []string         `db:"categories" json:"categories"`
	Stocks       []int32          `db:"stocks" json:"stocks"`
}

func (q *Queries) CreateManyProducts(ctx context.Context, arg CreateManyProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, CreateManyProducts,
		arg.Names,
		arg.Descriptions,
		arg.Prices,
		arg.Images,
		arg.Categories,
		arg.Stocks,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.Image,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const CreateProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description, price, image, category, stock)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, price, image, category, stock, created_at, updated_at
`

type CreateProductParams struct {
	Name        string         `db:"name" json:"name"`
	Description *string        `db:"description" json:"description"`
	Price       pgtype.Numeric `db:"price" json:"price"`
	Image       products.Image `db:"image" json:"image"`
	Category    []string       `db:"category" json:"category"`
	Stock       int32          `db:"stock" json:"stock"`
}

type CreateProductRow struct {
	ID          int32              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Price       pgtype.Numeric     `db:"price" json:"price"`
	Image       products.Image     `db:"image" json:"image"`
	Category    []string           `db:"category" json:"category"`
	Stock       int32              `db:"stock" json:"stock"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, CreateProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Image,
		arg.Category,
		arg.Stock,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Image,
		&i.Category,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DecrementProductStock = `-- name: DecrementProductStock :execrows
UPDATE products
        SET stock = stock - $1
WHERE id = $2 AND stock >= $1
`

type DecrementProductStockParams struct {
	Quantity int32 `db:"quantity" json:"quantity"`
	ID       int32 `db:"id" json:"id"`
}

func (q *Queries) DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, DecrementProductStock, arg.Quantity, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteProduct, id)
	return err
}

const GetProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, category, image, stock, created_at, updated_at FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, GetProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Image,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetProductForUpdate = `-- name: GetProductForUpdate :one
SELECT id, name, description, price, category, image, stock, created_at, updated_at FROM products
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetProductForUpdate(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, GetProductForUpdate, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Image,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListProducts = `-- name: ListProducts :many
SELECT id, name, description, price, category, image, stock, created_at, updated_at FROM products
ORDER BY id ASC
LIMIT $2 OFFSET $1
`

type ListProductsParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageSize   int32 `db:"page_size" json:"page_size"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, ListProducts, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.Image,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateProduct = `-- name: UpdateProduct :one
UPDATE products SET name = COALESCE($1, name), description = COALESCE($2, description), price = COALESCE($3, price), category = COALESCE($4, category), image = COALESCE($5, image), stock = COALESCE($6, stock), updated_at = NOW() WHERE id = $7 RETURNING id, name, description, price, category, image, stock, created_at, updated_at
`

type UpdateProductParams struct {
	Name        string         `db:"name" json:"name"`
	Description *string        `db:"description" json:"description"`
	Price       pgtype.Numeric `db:"price" json:"price"`
	Category    []string       `db:"category" json:"category"`
	Image       products.Image `db:"image" json:"image"`
	Stock       int32          `db:"stock" json:"stock"`
	ID          int32          `db:"id" json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, UpdateProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Category,
		arg.Image,
		arg.Stock,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.Image,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
