// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountProducts(ctx context.Context) (int64, error)
	CreateManyProducts(ctx context.Context, arg CreateManyProductsParams) ([]Product, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (int64, error)
	DeleteProduct(ctx context.Context, id int32) error
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetProductByID(ctx context.Context, id int32) (Product, error)
	GetProductForUpdate(ctx context.Context, id int32) (Product, error)
	ListOrderItems(ctx context.Context, orderID pgtype.UUID) ([]ListOrderItemsRow, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
